# Generated by Django 4.0.4 on 2022-05-04 21:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('prefix', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(8)])),
                ('description', models.TextField(blank=True, default='')),
                ('admins', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
