# Generated by Django 4.0.4 on 2022-05-10 06:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wireguard_manager.models.peering


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wireguard_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('public_key', models.CharField(max_length=50)),
                ('public_endpoint', models.CharField(blank=True, default='', max_length=64)),
                ('local_endpoint', models.CharField(blank=True, default='', max_length=64)),
                ('listen_port', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('other_addresses', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='networkblock',
            name='name',
            field=models.CharField(default='Network Block', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkblock',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Peering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_peering', models.BooleanField(default=False)),
                ('pre_shared_key', models.CharField(default=wireguard_manager.models.peering.new_psk, max_length=50)),
                ('peer_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wireguard_manager.device')),
                ('peer_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wireguard_manager.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='address_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wireguard_manager.networkblock'),
        ),
    ]
